# Data Extract / Transform / Load

In [1]:
# Dependencies
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

### CSV Files to DataFrame

In [2]:
df = pd.read_csv('../Data/team_data.csv')
df

,yearID,lgID,teamID,franchID,divID,Rank,G,Ghome,W,L,...,DP,FP,name,park,attendance,BPF,PPF,teamIDBR,teamIDlahman45,teamIDretro
0,1871,NaN,BS1,BNA,NaN,3,31,NaN,20,10,...,24,0.834,Boston Red Stockings,South End Grounds I,NaN,103,98,BOS,BS1,BS1
1,1871,NaN,CH1,CNA,NaN,2,28,NaN,19,9,...,16,0.829,Chicago White Stockings,Union Base-Ball Grounds,NaN,104,102,CHI,CH1,CH1
2,1871,NaN,CL1,CFC,NaN,8,29,NaN,10,19,...,15,0.818,Cleveland Forest Citys,National Association Grounds,NaN,96,100,CLE,CL1,CL1
3,1871,NaN,FW1,KEK,NaN,7,19,NaN,7,12,...,8,0.803,Fort Wayne Kekiongas,Hamilton Field,NaN,101,107,KEK,FW1,FW1
4,1871,NaN,NY2,NNA,NaN,5,33,NaN,16,17,...,14,0.840,New York Mutuals,Union Grounds (Brooklyn),NaN,90,88,NYU,NY2,NY2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2980,2021,NL,SLN,STL,C,2,162,81.0,90,72,...,137,0.986,St. Louis Cardinals,Busch Stadium III,2102530.0,92,92,STL,SLN,SLN
2981,2021,AL,TBA,TBD,E,1,162,81.0,100,62,...,130,0.986,Tampa Bay Rays,Tropicana Field,761072.0,92,91,TBR,TBA,TBA
2982,2021,AL,TEX,TEX,W,5,162,81.0,60,102,...,146,0.986,Texas Rangers,Globe Life Field,2110258.0,99,101,TEX,TEX,TEX
2983,2021,AL,TOR,TOR,E,4,162,80.0,91,71,...,122,0.984,Toronto Blue Jays,Sahlen Field,805901.0,102,101,TOR,TOR,TOR
2984,2021,NL,WAS,WSN,E,5,162,81.0,65,97,...,116,0.983,Washington Nationals,Nationals Park,1465543.0,95,96,WSN,MON,WAS

In [3]:
df.columns

Index(['yearID', 'lgID', 'teamID', 'franchID', 'divID', 'Rank', 'G', 'Ghome',
       'W', 'L', 'DivWin', 'WCWin', 'LgWin', 'WSWin', 'R', 'AB', 'H', '2B',
       '3B', 'HR', 'BB', 'SO', 'SB', 'CS', 'HBP', 'SF', 'RA', 'ER', 'ERA',
       'CG', 'SHO', 'SV', 'IPouts', 'HA', 'HRA', 'BBA', 'SOA', 'E', 'DP', 'FP',
       'name', 'park', 'attendance', 'BPF', 'PPF', 'teamIDBR',
       'teamIDlahman45', 'teamIDretro'],
      dtype='object')

In [4]:
df = df.fillna(0)
df

,yearID,lgID,teamID,franchID,divID,Rank,G,Ghome,W,L,...,DP,FP,name,park,attendance,BPF,PPF,teamIDBR,teamIDlahman45,teamIDretro
0,1871,0,BS1,BNA,0,3,31,0.0,20,10,...,24,0.834,Boston Red Stockings,South End Grounds I,0.0,103,98,BOS,BS1,BS1
1,1871,0,CH1,CNA,0,2,28,0.0,19,9,...,16,0.829,Chicago White Stockings,Union Base-Ball Grounds,0.0,104,102,CHI,CH1,CH1
2,1871,0,CL1,CFC,0,8,29,0.0,10,19,...,15,0.818,Cleveland Forest Citys,National Association Grounds,0.0,96,100,CLE,CL1,CL1
3,1871,0,FW1,KEK,0,7,19,0.0,7,12,...,8,0.803,Fort Wayne Kekiongas,Hamilton Field,0.0,101,107,KEK,FW1,FW1
4,1871,0,NY2,NNA,0,5,33,0.0,16,17,...,14,0.840,New York Mutuals,Union Grounds (Brooklyn),0.0,90,88,NYU,NY2,NY2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2980,2021,NL,SLN,STL,C,2,162,81.0,90,72,...,137,0.986,St. Louis Cardinals,Busch Stadium III,2102530.0,92,92,STL,SLN,SLN
2981,2021,AL,TBA,TBD,E,1,162,81.0,100,62,...,130,0.986,Tampa Bay Rays,Tropicana Field,761072.0,92,91,TBR,TBA,TBA
2982,2021,AL,TEX,TEX,W,5,162,81.0,60,102,...,146,0.986,Texas Rangers,Globe Life Field,2110258.0,99,101,TEX,TEX,TEX
2983,2021,AL,TOR,TOR,E,4,162,80.0,91,71,...,122,0.984,Toronto Blue Jays,Sahlen Field,805901.0,102,101,TOR,TOR,TOR
2984,2021,NL,WAS,WSN,E,5,162,81.0,65,97,...,116,0.983,Washington Nationals,Nationals Park,1465543.0,95,96,WSN,MON,WAS

In [5]:
Datt = df.loc[df['attendance'] > 0].copy()
Datt

,yearID,lgID,teamID,franchID,divID,Rank,G,Ghome,W,L,...,DP,FP,name,park,attendance,BPF,PPF,teamIDBR,teamIDlahman45,teamIDretro
240,1890,NL,BRO,LAD,0,1,129,0.0,86,43,...,92,0.940,Brooklyn Bridegrooms,Washington Park II,121412.0,101,97,BRO,BRO,BRO
242,1890,NL,BSN,ATL,0,5,134,0.0,76,57,...,77,0.935,Boston Beaneaters,South End Grounds II,147539.0,108,105,BSN,BSN,BSN
244,1890,NL,CHN,CHC,0,2,139,0.0,83,53,...,89,0.940,Chicago Colts,West Side Park I,102536.0,104,102,CHC,CHN,CHN
246,1890,NL,CIN,CIN,0,4,134,0.0,77,55,...,106,0.932,Cincinnati Reds,League Park I in Cincinnati,131980.0,101,101,CIN,CIN,CIN
247,1890,NL,CL4,CLV,0,7,136,0.0,44,88,...,108,0.929,Cleveland Spiders,National League Park,47478.0,94,97,CLV,CL4,CL4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2980,2021,NL,SLN,STL,C,2,162,81.0,90,72,...,137,0.986,St. Louis Cardinals,Busch Stadium III,2102530.0,92,92,STL,SLN,SLN
2981,2021,AL,TBA,TBD,E,1,162,81.0,100,62,...,130,0.986,Tampa Bay Rays,Tropicana Field,761072.0,92,91,TBR,TBA,TBA
2982,2021,AL,TEX,TEX,W,5,162,81.0,60,102,...,146,0.986,Texas Rangers,Globe Life Field,2110258.0,99,101,TEX,TEX,TEX
2983,2021,AL,TOR,TOR,E,4,162,80.0,91,71,...,122,0.984,Toronto Blue Jays,Sahlen Field,805901.0,102,101,TOR,TOR,TOR
2984,2021,NL,WAS,WSN,E,5,162,81.0,65,97,...,116,0.983,Washington Nationals,Nationals Park,1465543.0,95,96,WSN,MON,WAS

In [6]:
Datt.columns

Index(['yearID', 'lgID', 'teamID', 'franchID', 'divID', 'Rank', 'G', 'Ghome',
       'W', 'L', 'DivWin', 'WCWin', 'LgWin', 'WSWin', 'R', 'AB', 'H', '2B',
       '3B', 'HR', 'BB', 'SO', 'SB', 'CS', 'HBP', 'SF', 'RA', 'ER', 'ERA',
       'CG', 'SHO', 'SV', 'IPouts', 'HA', 'HRA', 'BBA', 'SOA', 'E', 'DP', 'FP',
       'name', 'park', 'attendance', 'BPF', 'PPF', 'teamIDBR',
       'teamIDlahman45', 'teamIDretro'],
      dtype='object')

In [7]:
Dreduced = Datt[['teamID', 'franchID', 'name', 'G', 'Ghome', 'yearID', 'Rank', 'W', 'L', 'park', 'attendance', 'HR', 'R', 'DivWin', 'WCWin', 'LgWin', 'WSWin']].copy()
Dreduced

,teamID,franchID,name,G,Ghome,yearID,Rank,W,L,park,attendance,HR,R,DivWin,WCWin,LgWin,WSWin
240,BRO,LAD,Brooklyn Bridegrooms,129,0.0,1890,1,86,43,Washington Park II,121412.0,43,884,0,0,Y,N
242,BSN,ATL,Boston Beaneaters,134,0.0,1890,5,76,57,South End Grounds II,147539.0,31,763,0,0,N,N
244,CHN,CHC,Chicago Colts,139,0.0,1890,2,83,53,West Side Park I,102536.0,67,847,0,0,N,N
246,CIN,CIN,Cincinnati Reds,134,0.0,1890,4,77,55,League Park I in Cincinnati,131980.0,27,753,0,0,N,N
247,CL4,CLV,Cleveland Spiders,136,0.0,1890,7,44,88,National League Park,47478.0,21,630,0,0,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2980,SLN,STL,St. Louis Cardinals,162,81.0,2021,2,90,72,Busch Stadium III,2102530.0,198,706,N,Y,N,N
2981,TBA,TBD,Tampa Bay Rays,162,81.0,2021,1,100,62,Tropicana Field,761072.0,222,857,Y,N,N,N
2982,TEX,TEX,Texas Rangers,162,81.0,2021,5,60,102,Globe Life Field,2110258.0,167,625,N,N,N,N
2983,TOR,TOR,Toronto Blue Jays,162,80.0,2021,4,91,71,Sahlen Field,805901.0,262,846,N,N,N,N
2984,WAS,WSN,Washington Nationals,162,81.0,2021,5,65,97,Nationals Park,1465543.0,182,724,N,N,N,N

In [8]:
Dnew = Dreduced.loc[Dreduced['Ghome'] > 0.0].copy()

Dnew

,teamID,franchID,name,G,Ghome,yearID,Rank,W,L,park,attendance,HR,R,DivWin,WCWin,LgWin,WSWin
383,BLA,NYY,Baltimore Orioles,134,66.0,1901,5,68,65,Oriole Park,141952.0,24,760,0,0,N,0
384,BOS,BOS,Boston Americans,138,69.0,1901,2,79,57,Huntington Avenue Grounds,289448.0,37,759,0,0,N,0
385,BRO,LAD,Brooklyn Superbas,137,68.0,1901,3,79,57,Washington Park III,198200.0,32,744,0,0,N,0
386,BSN,ATL,Boston Beaneaters,140,70.0,1901,5,69,69,South End Grounds III,146502.0,28,531,0,0,N,0
387,CHA,CHW,Chicago White Sox,137,71.0,1901,1,83,53,South Side Park II,354350.0,32,819,0,0,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2980,SLN,STL,St. Louis Cardinals,162,81.0,2021,2,90,72,Busch Stadium III,2102530.0,198,706,N,Y,N,N
2981,TBA,TBD,Tampa Bay Rays,162,81.0,2021,1,100,62,Tropicana Field,761072.0,222,857,Y,N,N,N
2982,TEX,TEX,Texas Rangers,162,81.0,2021,5,60,102,Globe Life Field,2110258.0,167,625,N,N,N,N
2983,TOR,TOR,Toronto Blue Jays,162,80.0,2021,4,91,71,Sahlen Field,805901.0,262,846,N,N,N,N
2984,WAS,WSN,Washington Nationals,162,81.0,2021,5,65,97,Nationals Park,1465543.0,182,724,N,N,N,N

In [11]:
Dnew['Ghome'] = Dnew['Ghome'].astype(int)
Dnew['attendance'] = Dnew['attendance'].astype(int)
Dnew.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2556 entries, 383 to 2984
Data columns (total 17 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   teamID      2556 non-null   object
 1   franchID    2556 non-null   object
 2   name        2556 non-null   object
 3   G           2556 non-null   int64
 4   Ghome       2556 non-null   int32
 5   yearID      2556 non-null   int64
 6   Rank        2556 non-null   int64
 7   W           2556 non-null   int64
 8   L           2556 non-null   int64
 9   park        2556 non-null   object
 10  attendance  2556 non-null   int32
 11  HR          2556 non-null   int64
 12  R           2556 non-null   int64
 13  DivWin      2556 non-null   object
 14  WCWin       2556 non-null   object
 15  LgWin       2556 non-null   object
 16  WSWin       2556 non-null   object
dtypes: int32(2), int64(7), object(8)
memory usage: 339.5+ KB

In [13]:
categoricalData = [column for column in Dnew.columns if Dnew[column].dtypes == 'O']
categoricalData

['teamID', 'franchID', 'name', 'park', 'DivWin', 'WCWin', 'LgWin', 'WSWin']

In [14]:
Dnew['yearID'].min()

1901

In [15]:

Dclean = Dnew.loc[Dnew['yearID'] >= 1990].copy()
Dclean

,teamID,franchID,name,G,Ghome,yearID,Rank,W,L,park,attendance,HR,R,DivWin,WCWin,LgWin,WSWin
2047,ATL,ATL,Atlanta Braves,162,81,1990,6,65,97,Atlanta-Fulton County Stadium,980129,162,682,N,0,N,N
2048,BAL,BAL,Baltimore Orioles,161,80,1990,5,76,85,Memorial Stadium,2415189,132,669,N,0,N,N
2049,BOS,BOS,Boston Red Sox,162,81,1990,1,88,74,Fenway Park II,2528986,106,699,Y,0,N,N
2050,CAL,ANA,California Angels,162,81,1990,4,80,82,Anaheim Stadium,2555688,147,690,N,0,N,N
2051,CHA,CHW,Chicago White Sox,162,80,1990,2,94,68,Comiskey Park,2002357,106,682,N,0,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2980,SLN,STL,St. Louis Cardinals,162,81,2021,2,90,72,Busch Stadium III,2102530,198,706,N,Y,N,N
2981,TBA,TBD,Tampa Bay Rays,162,81,2021,1,100,62,Tropicana Field,761072,222,857,Y,N,N,N
2982,TEX,TEX,Texas Rangers,162,81,2021,5,60,102,Globe Life Field,2110258,167,625,N,N,N,N
2983,TOR,TOR,Toronto Blue Jays,162,80,2021,4,91,71,Sahlen Field,805901,262,846,N,N,N,N
2984,WAS,WSN,Washington Nationals,162,81,2021,5,65,97,Nationals Park,1465543,182,724,N,N,N,N

In [16]:
Dclean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 908 entries, 2047 to 2984
Data columns (total 17 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   teamID      908 non-null    object
 1   franchID    908 non-null    object
 2   name        908 non-null    object
 3   G           908 non-null    int64
 4   Ghome       908 non-null    int32
 5   yearID      908 non-null    int64
 6   Rank        908 non-null    int64
 7   W           908 non-null    int64
 8   L           908 non-null    int64
 9   park        908 non-null    object
 10  attendance  908 non-null    int32
 11  HR          908 non-null    int64
 12  R           908 non-null    int64
 13  DivWin      908 non-null    object
 14  WCWin       908 non-null    object
 15  LgWin       908 non-null    object
 16  WSWin       908 non-null    object
dtypes: int32(2), int64(7), object(8)
memory usage: 120.6+ KB

In [17]:
Dclean['att_per_game'] = Dclean['attendance'] / Dclean['Ghome']
Dclean

,teamID,franchID,name,G,Ghome,yearID,Rank,W,L,park,attendance,HR,R,DivWin,WCWin,LgWin,WSWin,att_per_game
2047,ATL,ATL,Atlanta Braves,162,81,1990,6,65,97,Atlanta-Fulton County Stadium,980129,162,682,N,0,N,N,12100.358025
2048,BAL,BAL,Baltimore Orioles,161,80,1990,5,76,85,Memorial Stadium,2415189,132,669,N,0,N,N,30189.862500
2049,BOS,BOS,Boston Red Sox,162,81,1990,1,88,74,Fenway Park II,2528986,106,699,Y,0,N,N,31222.049383
2050,CAL,ANA,California Angels,162,81,1990,4,80,82,Anaheim Stadium,2555688,147,690,N,0,N,N,31551.703704
2051,CHA,CHW,Chicago White Sox,162,80,1990,2,94,68,Comiskey Park,2002357,106,682,N,0,N,N,25029.462500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2980,SLN,STL,St. Louis Cardinals,162,81,2021,2,90,72,Busch Stadium III,2102530,198,706,N,Y,N,N,25957.160494
2981,TBA,TBD,Tampa Bay Rays,162,81,2021,1,100,62,Tropicana Field,761072,222,857,Y,N,N,N,9395.950617
2982,TEX,TEX,Texas Rangers,162,81,2021,5,60,102,Globe Life Field,2110258,167,625,N,N,N,N,26052.567901
2983,TOR,TOR,Toronto Blue Jays,162,80,2021,4,91,71,Sahlen Field,805901,262,846,N,N,N,N,10073.762500
2984,WAS,WSN,Washington Nationals,162,81,2021,5,65,97,Nationals Park,1465543,182,724,N,N,N,N,18093.123457